<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DiskAnalyzer.Core\DiskAnalyzer.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>DiskAnalyzer</AssemblyName>
  </PropertyGroup>

</Project>
